root: true
env:
  browser: true
  jest/globals: true
extends:
  - eslint:recommended
  - prettier # eslint-config-prettier
  - plugin:@typescript-eslint/recommended
plugins:
  - jest # eslint-plugin-jest
rules:
  '@typescript-eslint/ban-ts-comment': off # temporary disable while addressing existing violations
  '@typescript-eslint/consistent-type-exports': error
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/no-empty-function': off
